# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: Default Scanner

on:
  push:
    branches: [ "main", "#*", "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "#*", "develop" ]
    
jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install All
        run: npm run install-all

      - name: Run ESLint
        run: npx eslint .

      - name: Run Backend Tests
        working-directory: backend/
        run: npm run test
